name: my_app
description: "EPI Core - A Flutter application"
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: '>=3.22.3'

dependencies:
  gap: ^3.0.1
  equatable: ^2.0.5  
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  logger: ^1.4.0
  url_launcher: ^6.3.0
  # sentry: ^9.6.0    
  # sentry_flutter: ^9.6.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0 
  permission_handler: ^12.0.1
  path_provider: ^2.1.4
  audioplayers: ^6.5.1
  just_audio: ^0.10.5
  uuid: ^4.5.1
  flutter_cube: ^0.1.1
  shared_preferences: ^2.2.2
  device_info_plus: ^10.1.0
  package_info_plus: ^8.0.0
  share_plus: ^11.1.0
  json_annotation: ^4.9.0
  image: ^4.1.7
  image_picker: ^1.0.4
  crypto: ^3.0.3
  vector_math: ^2.1.4
  # record: ^5.2.1  # Temporarily disabled due to version conflicts
  pdf: ^3.10.7
  path: ^1.8.3
  
  # Firebase Dependencies
  # Uncomment these lines when you need Firebase functionality
  # To use Firebase, you'll also need to:
  # 1. Create a Firebase project at https://console.firebase.google.com/
  # 2. Add your app to the Firebase project
  # 3. Download google-services.json and place it in android/app/
  # 4. Run 'flutterfire configure' to generate firebase_options.dart
  # 5. Uncomment the Firebase initialization in lib/main/bootstrap.dart
  # firebase_core: ^3.11.0
  # cloud_firestore: ^5.6.3
  # firebase_auth: ^5.4.2

dev_dependencies:
  build_runner: ^2.4.5
  flutter_lints: ^3.0.1
  # sentry_dart_plugin: ^3.1.1  
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  json_serializable: ^6.8.0    
  mocktail: ^1.0.4  
  hive_generator: ^2.0.1
  bloc_test: ^10.0.0
  sentry_dart_plugin: ^3.1.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/audio/
    - assets/insights/rules_v1.json


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/steve.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/steve.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/steve.png"
    icon_size: 48 # min:48, max:256, default 48
  macos:
    generate: true
    image_path: "assets/images/steve.png"

# sentry:
#   project: epi-core-a9f488
#   org: steve-jm
#   auth_token: sntrys_eyJpYXQiOjE3NDI4MDUxNzIuMzc4ODg1LCJ1cmwiOiJodHRwczovL3NlbnRyeS5pbyIsInJlZ2lvbl91cmwiOiJodHRwczovL3VzLnNlbnRyeS5pbyIsIm9yZyI6InN0ZXZlLWptIn0=_r1Ru3oYiUqebkmQS3QTJdTQ3wbgfn1mPKhhInVPlgA
#   upload_source_maps: true
#   ignore_missing: true